name: CI + CD

on:
  push:    
  pull_request:
    branches: [ develop, staging, master ]
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Compile
        run: echo Compile Step...
    
  DeployDev:
    name: Deploy to Dev 
    if: github.event_name == 'pull_request' && github.event.ref == 'refs/heads/develop'
    needs: [Build]
    runs-on: ubuntu-latest
    environment: 
      name: Development
      url: 'http://someweb.com'
    steps:
      - name: Deploy
        run: echo I am deploying! 
    
  DeployPreproduction:
    name: Deploy to Preproduction 
    if: ithub.event_name == 'pull_request' && github.event.ref == 'refs/heads/staging'
    needs: [DeployDev]
    runs-on: ubuntu-latest
    environment: 
      name: Preproduction
      url: 'http://someweb.com'
    steps:
      - name: Deploy
        run: echo I am deploying! 
            
  DeployProd:
    name: Deploy to Production 
    if: ithub.event_name == 'pull_request' && github.event.ref == 'refs/heads/master'
    needs: [DeployPreproduction]
    runs-on: ubuntu-latest
    environment: 
      name: Production
      url: 'http://someweb.com'
    steps:
      - name: Deploy
        run: echo I am deploying! 