name: CI + CD

on:  
  push:  
  pull_request:  
    branches: [ develop, staging ]
    types: 
      - closed
  release:
    types:
      - created
  workflow_dispatch:
env:
  GITHUB_CONTEXT: ${{ toJson(github) }}

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Compile
        run: echo ${{ github.event_name }} - ${{ github.base_ref }} - ${{ github.ref }} - ${{ github.event.pull_request.merged }} - ${{ github.event.action }} $GITHUB_CONTEXT - Compile Step..
    
  DeployDev:
    name: Deploy to Dev 
    if: github.event_name == 'pull_request' && github.base_ref == 'develop'
    needs: [Build]
    runs-on: ubuntu-latest
    environment: 
      name: Development
      url: 'http://someweb.com'
    steps:
      - name: Deploy
        run: echo Deploying Dev....   
    
  DeployPreproduction:
    name: Deploy to Preproduction 
    if: github.event_name == 'pull_request' && github.base_ref == 'staging'
    needs: [Build]
    runs-on: ubuntu-latest
    environment: 
      name: Preproduction
      url: 'http://someweb.com'
    steps:
      - name: Deploy
        run: echo I am deploying!! 
            
  DeployProduction:
    name: Deploy to Production 
    if: github.event_name == 'release'
    needs: [DeployPreproduction]
    runs-on: ubuntu-latest
    environment: 
      name: Production
      url: 'http://someweb.com'
    steps:
      - name: Deploy
        run: echo I am deploying! 