name: pipeline nueva

on:  
  push:  
    branches-ignore: [ develop, staging ]    

  pull_request:  
    branches: [ develop, staging ]

  release:
    types: [ created ]


env:
  GITHUB_CONTEXT: ${{ toJson(github) }}

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: devopsviewnext/workflows_generic@v1
        with:
          workflow: CI + CD
          token: ${{ secrets.PERSONAL_TOKEN }}


  