name: pipeline nueva

on:  
  push:  

env:
  GITHUB_CONTEXT: ${{ toJson(github) }}

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: devopsviewnext/workflows_generic@v2
        with:
          workflow: CICDJAVA
          token: ${{ secrets.PERSONAL_TOKEN }}


  